const actions = {
    ADD_INVENTORY: 'ADD_INVENTORY',
    REMOVE_INVENTORY: 'REMOVE_INVENTORY',
    EDIT_INVENTORY: 'EDIT_INVENTORY',
    REMOVE_INVENTORY_TYPE: 'REMOVE_INVENTORY_TYPE',
    ADD_INVENTORY_TYPE: 'ADD_INVENTORY_TYPE',
    EDIT_INVENTORY_TYPE: 'EDIT_INVENTORY_TYPE',
    EDIT_INVENTORY_OBJECT_TITLE: 'EDIT_INVENTORY_OBJECT_TITLE'
};

export default actions;